resource_registry:
    OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
    OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
    OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml
    OS::TripleO::NodeUserData: first-boot.yaml
    OS::TripleO::NodeExtraConfigPost: post-install.yaml

parameter_defaults:
    InternalApiNetCidr: 172.17.1.0/24
    StorageNetCidr: 172.17.3.0/24
    StorageMgmtNetCidr: 172.17.4.0/24
    TenantNetCidr: 172.17.2.0/24
    ExternalNetCidr: 10.9.88.0/24
    ControlPlaneSubnetCidr: '24'
    InternalApiAllocationPools: [{'start': '172.17.1.10', 'end': '172.17.1.200'}]
    StorageAllocationPools: [{'start': '172.17.3.10', 'end': '172.17.3.200'}]
    StorageMgmtAllocationPools: [{'start': '172.17.4.10', 'end': '172.17.4.200'}]
    TenantAllocationPools: [{'start': '172.17.2.10', 'end': '172.17.2.200'}]
    ExternalAllocationPools: [{'start': '10.9.88.109',             'end': '10.9.88.118'}]     
    ExternalInterfaceDefaultRoute: 10.9.88.254
    InternalApiNetworkVlanID: 201
    StorageNetworkVlanID: 203
    StorageMgmtNetworkVlanID: 204
    ExternalNetworkVlanID: 1
    TenantNetworkVlanID: 202
    NeutronExternalNetworkBridge: "''"
    ControlPlaneDefaultRoute: 192.168.21.1
    EC2MetadataIp: 192.168.21.1
    DnsServers: ["10.11.5.19", "10.10.160.2", "10.5.30.160"]

    NeutronNetworkType: 'vlan'
    NeutronBridgeMappings: 'sriov:br-sriov'
    NeutronNetworkVLANRanges: 'sriov:215:219'
    NeutronMechanismDrivers: "openvswitch,sriovnicswitch"
    NovaPCIPassthrough:
    - devname: "p5p2"
      physical_network: "sriov"
    NeutronSupportedPCIVendorDevs: ['8086:1528', '8086:10ed', '8086:1515']
    NeutronPhysicalDevMappings: "sriov:p5p2"
    NeutronSriovNumVFs: "p5p2:5"
    NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter']
    ComputeKernelArgs: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=12"
    HostIsolatedCoreList: "'2,4,6,8,10,12,14,18,20,22,24,26,28,30'"
